# Generated by Django 4.2.5 on 2023-09-27 02:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0'), message='Rating must be 0.0 or greater.'), django.core.validators.MaxValueValidator(Decimal('5.0'), message='Rating must be 5.0 or less.')]),
        ),
    ]
